version: "{build}"

environment:
  matrix:
    - ARCHITECTURE: "x86"
      PYTHON_VERSION: "3.7"
      PYTHON: "C:\\Python37"
    - ARCHITECTURE: "x64"
      PYTHON_VERSION: "3.7"
      PYTHON: "C:\\Python37-x64"
    - ARCHITECTURE: "x86"
      PYTHON_VERSION: "3.8"
      PYTHON: "C:\\Python38"
    - ARCHITECTURE: "x64"
      PYTHON_VERSION: "3.8"
      PYTHON: "C:\\Python38-x64"
    - ARCHITECTURE: "x86"
      PYTHON_VERSION: "3.9"
      PYTHON: "C:\\Python39"
    - ARCHITECTURE: "x64"
      PYTHON_VERSION: "3.9"
      PYTHON: "C:\\Python39-x64"
    - ARCHITECTURE: "x86"
      PYTHON_VERSION: "3.10"
      PYTHON: "C:\\Python310"
    - ARCHITECTURE: "x64"
      PYTHON_VERSION: "3.10"
      PYTHON: "C:\\Python310-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - python -m pip install -U pip
  - python -m pip install -U -r requirements_ci.txt
  # git repositories for testing
  - git clone https://github.com/mbdevpl/argunparse ../argunparse
  - git clone https://github.com/mbdevpl/transpyle ../transpyle
  - git clone https://github.com/mbdevpl/typed-astunparse ../typed-astunparse

build: off

test_script:
  - set TEST_PACKAGING=1
  - python -m coverage run --branch --source . -m unittest -v

after_test:
  - python -m coverage report --show-missing
  - codecov
